### PR TITLE
add university of houston

### PR DESCRIPTION
**Pull request by metaweidner**

### CODE REVIEW

**Comment by metaweidner** [comment]
@scottythered Did I submit this pull request on the right branch? Wasn't sure whether I should submit on `dev` or `master`.

**Comment by scottythered** [comment]
Dev is the place to do it! I'll take a look in the next day or so.

**Comment by metaweidner** [comment]
Thanks for merging @scottythered. Is there any way to just link to the website provided in the pull request instead of converting to PDF? There's so much that's missing when it's converted to a flat file.

**Comment by scottythered** [comment]
I'll ask the dev group. Part of the purpose of the project was to have hard copies stored in the repo, but minds may change.

**Comment by metaweidner** [comment]
Cool. Our MAP is still under development, so that PDF may be out of date sooner rather than later. Even when it becomes more stable, I'd consider its website and Github repo a better reflection of its full scope and version history:

- https://vocab.lib.uh.edu/bcdams-map
- https://github.com/uhlibraries-digital/bcdams-map

**Pull request merged**
